[package]
name = "swagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.23"
mapper={path="../mapper"}
reqwest = { version = "0.11", features = ["json","rustls-tls"],default_features=false }
futures = "0.3"
strum = "0.23"
strum_macros = "0.23"
url="^2"
colored = "2.0.0"
