on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Step
      run: |
          echo "THINGS"
  build:
    runs-on: ubuntu-latest
    #Our Job
    steps:
    - name: Get OAS
      run: |
        aws apigateway get-export --parameters extensions='integrations' --rest-api-id 123 --stage-name prod --export-type oas30 ./swagger.json
      env: # PLEASE MAKE SURE THE SECRETS ARE DEFINED AS ENVIRONMENT VARIABLES 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: $REGION

    - name: Run Docker
      run: |
        docker run --mount type=bind,source=“$(pwd)“,destination=/home try-cherry:latest cherrybomb oas -f home/swagger.json --min-severity Medium
