on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        run: >
          docker run
          --mount type=bind,source=path/to/sag.json,destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb oas -f home/swagger.json --min-severity Medium --api-key=bd6d9e4ca4414a44a85978eec024484b

      - name: Run Param Table
        run: >
          docker run
          --mount type=bind,source=path/to/sag.json,destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb param-table -f home/swagger.json --api-key=bd6d9e4ca4414a44a85978eec024484b

      - name: Run Ep Table
        run: >
          docker run
          --mount type=bind,source=path/to/sag.json,destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb ep-table -f home/swagger.json --api-key=bd6d9e4ca4414a44a85978eec024484b
