on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get OAS
        run: |
          curl https://www.filemail.com/d/dpocrwphlhjvikf -o swagger.json

      - name: Run Docker
        run: >
          docker run
          --mount type=bind,source="$(pwd)",destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb oas -f home/swagger.json --min-severity Medium --api-key=Couldn't get API key

      - name: Run Param Table
        run: >
          docker run
          --mount type=bind,source="$(pwd)",destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb param-table -f home/swagger.json --api-key=Couldn't get API key

      - name: Run Ep Table
        run: >
          docker run
          --mount type=bind,source="$(pwd)",destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb ep-table -f home/swagger.json --api-key=Couldn't get API key
