on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker
        run: >
          docker run
          --mount type=bind,source=gfgf,destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb oas -f home/swagger.json --min-severity Medium --api-key=Couldn’t get API key auth --type 0 --token Igal:MyPassword
      - name: Run Param Table
        run: >
          docker run
          --mount type=bind,source=gfgf,destination=/home public.ecr.aws/t1d5k0l0/cherrybomb:latest
          cherrybomb param-table -f home/swagger.json --api-key=Couldn’t get API key
