on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Step
      run: |
          echo "THINGS"
  build:
    runs-on: ubuntu-latest
    #Our Job
    steps:
    - name: Get OAS
      env:
        SP_CLIENT_ID: 123 #${{ secrets.SP_CLIENT_ID }}
        SP_CLIENT_SECRET: 234 #${{ secrets.SP_CLIENT_SECRET }}
        SP_TENANT_ID:  12 #${{ secrets.SP_TENANT_ID }}
        AZURE_SUBSCRIPTION_NAME: asd #${{ secrets.AZURE_SUBSCRIPTION_NAME }}
      run: |
        $ApiMgmtContext = New-AzApiManagementContext -ResourceGroupName asdf -ServiceName sdg
        Export-AzApiManagementApi -Context $ApiMgmtContext -ApiId $ssd12 -SpecificationFormat OpenApiJson -SaveAs ./swagger.json
        shell: pwsh
    - name: Run Docker
      run: |
            docker run --mount type=bind,source="$(pwd)",destination=/home try-cherry:latest cherrybomb oas -f home/swagger.json --min-severity Medium
            docker run --mount type=bind,source="$(pwd)",destination=/home try-cherry:latest cherrybomb param-table -f home/swagger.json
            docker run --mount type=bind,source="$(pwd)",destination=/home try-cherry:latest cherrybomb ep-table -f home/swagger.json
